name: RhythmMarket
main: me.lorenzop.webauctionplus.WebAuctionPlus
version: 1.1.14
author: lorenzop customised and updated by pablo67340.
website: http://webauctionplus.com/
depend: [Vault]
softdepend: [SignLink]
commands:
  rm:
    description: RhythmMarket
    usage: Use "/rm register [somepassword]" to set your password, then log into the RhythmMarket on the website.
permissions:
  rm.*:
    description: Gives access to all WebAuction commands
    default: false
    children:
      rm.use.mailbox: true
      rm.use.withdraw.money: true
      rm.use.deposit.money: true
      rm.announcer.receive: true
      rm.create.sign.deposit: true
      rm.create.sign.withdraw: true
      rm.create.sign.mailbox: true
      rm.create.sign.recent: true
      rm.create.sign.shout: true
      rm.password.create: true
      rm.password.change: true
      rm.canbuy: true
      rm.cansell: true
      rm.remove: true
      rm.webadmin: true
      rm.reload: true
      rm.save: true
  rm.use.*:
    description: Gives access to all WebAuction commands
    default: false
    children:
      rm.use.mailbox: true
      rm.use.withdraw.money: true
      rm.use.deposit.money: true
      rm.announcer.receive: true
      rm.password.create: true
      rm.password.change: true
      rm.canbuy: true
      rm.cansell: true
  rm.create.*:
    description: Gives access to all create and remove sign permissions
    default: false
    children:
      rm.create.sign.mailbox: true
      rm.create.sign.deposit: true
      rm.create.sign.withdraw: true
      rm.create.sign.recent: true
      rm.create.sign.shout: true
      rm.remove: true
  rm.password.*:
    description: Gives access to create an account or change password
    default: false
    children:
      rm.password.create: true
      rm.password.change: true
  rm.use.mailbox:
    description: Lets you use the mailbox
    default: true
  rm.use.withdraw.money:
    description: Lets you withdraw money from web account
    default: true
  rm.use.deposit.money:
    description: Lets you deposit money to web account
    default: true
  rm.announcer.receive:
    description: Let you see announcements in chat
    default: true
  rm.password.create:
    description: Lets you create a new account for the website
    default: true
  rm.password.change:
    description: Lets you change your password for the website
    default: true
  rm.canbuy:
    description: Lets you buy items on the website
    default: true
  rm.cansell:
    description: Lets you sell items on the website
    default: true
  rm.create.sign.mailbox:
    description: Lets you create mailbox signs
    default: op
  rm.create.sign.deposit:
    description: Lets you create money deposit points
    default: op
  rm.create.sign.withdraw:
    description: Lets you create money withdraw points
    default: op
  rm.create.sign.recent:
    description: Lets you create a sign to display recent auctions created
    default: op
  rm.create.sign.shout:
    description: Lets you create a sign to shout to all players nearby when a new auction is made
    default: op
  rm.remove:
    description: Lets you remove signs
    default: op
  rm.webadmin:
    description: Lets you change other peoples data via website
    default: op
  rm.reload:
    description: Reloads the WebAuctionPlus config.yml
    default: op
  rm.save:
    description: Saves the WebAuctionPlus config.yml
    default: op
